---

# *** Update package list, and upgrade installed packages.

- name: Update and upgrade installed packages
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: update-upgrade
    apply: { tags: always }
  tags: update-upgrade

# *** Install build essentials.

- name: Install package group "build essentials"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-build-essentials
    apply: { tags: always }
  tags: install-build-essentials

# *** Install new packages, grouped by functionality.

- name: Install package group "install-desktop-abcde"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-abcde
    apply: { tags: always }
  tags: install-desktop-abcde
  # ISOFF/2023-03-24: I haven't worked with MP3 files or audio apps in a spell.
  # OPTIN/2023-04-28: To support site.yml tag inheritence (e.g., `--tags
  # zoidy_mintyfresh`), use obtuse `when` test instead of 'never' tag.
  # - Use explicit `--tags install-desktop-abcde` to run this task.
  when: "'install-desktop-abcde' in ansible_run_tags"

- name: Install package group "install-desktop-audio"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-audio
    apply: { tags: always }
  tags: install-desktop-audio

- name: Install package group "install-desktop-core"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-core
    apply: { tags: always }
  tags: install-desktop-core

- name: Install package group "install-desktop-docs"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-docs
    apply: { tags: always }
  tags: install-desktop-docs

- name: Install package group "install-desktop-email"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-email
    apply: { tags: always }
  tags: install-desktop-email

- name: Install package group "install-desktop-font"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-font
    apply: { tags: always }
  tags: install-desktop-font

- name: Install package group "install-desktop-image"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-image
    apply: { tags: always }
  tags: install-desktop-image

- name: Install package group "install-develop-android"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-android
    apply: { tags: always }
  tags: install-develop-android

- name: Install package group "install-develop-dbms"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-dbms
    apply: { tags: always }
  tags: install-develop-dbms

- name: Install package group "install-develop-fortunes"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-fortunes
    apply: { tags: always }
  tags: install-develop-fortunes

- name: Install package group "install-develop-grep"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-grep
    apply: { tags: always }
  tags: install-develop-grep

- name: Install package group "install-develop-image"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-image
    apply: { tags: always }
  tags: install-develop-image

- name: Install package group "install-develop-lang"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-lang
    apply: { tags: always }
  tags: install-develop-lang

- name: Install package group "install-develop-misc"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-misc
    apply: { tags: always }
  tags: install-develop-misc

- name: Install package group "install-develop-net"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-net
    apply: { tags: always }
  tags: install-develop-net, install-develop-net-wireshark

- name: Install package group "install-develop-perl"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-perl
    apply: { tags: always }
  tags: install-develop-perl

- name: Install package group "install-develop-python"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-python
    apply: { tags: always }
  tags: install-develop-python

- name: Install package group "install-develop-ruby"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-ruby
    apply: { tags: always }
  tags: install-develop-ruby

- name: Install package group "install-develop-sec"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-sec
    apply: { tags: always }
  tags: install-develop-sec

- name: Install package group "install-develop-spatial"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-spatial
    apply: { tags: always }
  tags: install-develop-spatial

- name: Install package group "install-develop-terminal"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-terminal
    apply: { tags: always }
  tags: install-develop-terminal

- name: Install package group "install-develop-text"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-text
    apply: { tags: always }
  tags: install-develop-text

- name: Install package group "install-develop-vcs"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-vcs
    apply: { tags: always }
  tags: install-develop-vcs

- name: Install package group "install-develop-vim"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-vim
    apply: { tags: always }
  tags: install-develop-vim

- name: Install package group "install-develop-web"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-web
    apply: { tags: always }
  tags: install-develop-web

# *** Install new packages for specific distributions.

- name: Install package group "install-distro-14.04"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-14.04
    apply: { tags: always }
  tags: install-distro-14.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 17

- name: Install package group "install-distro-16.04"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-16.04
    apply: { tags: always }
  tags: install-distro-16.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 18

- name: Install package group "install-distro-18.04"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-18.04
    apply: { tags: always }
  tags: install-distro-18.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 19

- name: Install package group "install-distro-22.04"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-22.04
    apply: { tags: always }
  tags: install-distro-22.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 21

# *** Flatpaks

- name: Install package group "install-flatpaks"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-flatpaks
    apply: { tags: always }
  tags: install-flatpaks

- name: Load tasks to create flatpak update timer task
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: install-flatpaks-automatic-updates
    apply: { tags: always }
  tags: install-flatpaks-automatic-updates

# *** Perform sudo setup operations (I'm too lazy to put in other Galaxy Role).

- name: Determine if host is “Desktop” or “Laptop”
  # (lb): Response should be either "Desktop" or "Notebook", at least what I've seen.
  ansible.builtin.shell: dmidecode --string chassis-type
  become: yes
  register: chassis_type
  tags: laptop-lid-disable-wake-on

- name: Load tasks to Deactivate Reactive Laptop Lid Response
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: laptop-lid-disable-wake-on
    apply: { tags: always }
  tags: laptop-lid-disable-wake-on
  when: chassis_type.stdout == 'Notebook'

# ***

- name: Load tasks to Customize Log on Greeter Screen Background
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: log-on-screen-background
    apply: { tags: always }
  tags: log-on-screen-background

# ***

- name: "Enable 'Remove obsolete kernels and dependencies'"
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: mintupdate-automation-autoremove
    apply: { tags: always }
  tags: mintupdate-automation-autoremove

# ***

- name: Load tasks to Lock Sessions on Power Suspend
  ansible.builtin.include_role:
    name: zoidy_mintyfresh
    tasks_from: power-suspend-lock-sessions
    apply: { tags: always }
  tags: power-suspend-lock-sessions

