---

# ******************************************************
# *** APT packages (distro-version-agnostic)

# *** Update package list, and upgrade installed packages.

- name: Update and upgrade installed packages
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: update-upgrade
    apply: { tags: always }
  tags: update-upgrade

# *** Install build essentials.

- name: Install package group "build essentials"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-build-essentials
    apply: { tags: always }
  tags: install-build-essentials

# *** Install new packages, grouped by functionality.

- name: Install package group "install-desktop-abcde"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-abcde
    apply: { tags: always }
  tags: install-desktop-abcde
  # ISOFF/2023-03-24: I haven't worked with MP3 files or audio apps in a spell.
  # OPTIN/2023-04-28: To support site.yml tag inheritence (e.g., `--tags
  # zoidy_captivator`), use obtuse `when` test instead of 'never' tag.
  # - USAGE: Use explicit `--tags install-desktop-abcde` to run this task.
  when: "'install-desktop-abcde' in ansible_run_tags"

- name: Install package group "install-desktop-audio"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-audio
    apply: { tags: always }
  tags: install-desktop-audio

- name: Install package group "install-desktop-core"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-core
    apply: { tags: always }
  tags: install-desktop-core

- name: Install package group "install-desktop-docs"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-docs
    apply: { tags: always }
  tags: install-desktop-docs

- name: Install package group "install-desktop-email"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-email
    apply: { tags: always }
  tags: install-desktop-email

- name: Install package group "install-desktop-font"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-font
    apply: { tags: always }
  tags: install-desktop-font

- name: Install package group "install-desktop-image"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-image
    apply: { tags: always }
  tags: install-desktop-image

- name: Install package group "install-desktop-media"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-media
    apply: { tags: always }
  tags: install-desktop-media

- name: Install package group "install-desktop-misc"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-misc
    apply: { tags: always }
  tags: install-desktop-misc

- name: Install package group "install-desktop-spotify"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-desktop-spotify
    apply: { tags: always }
  tags: install-desktop-spotify

- name: Install package group "install-develop-android"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-android
    apply: { tags: always }
  tags: install-develop-android

- name: Install package group "install-develop-dbms"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-dbms
    apply: { tags: always }
  tags: install-develop-dbms

- name: Install package group "install-develop-fortunes"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-fortunes
    apply: { tags: always }
  tags: install-develop-fortunes

- name: Install package group "install-develop-grep"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-grep
    apply: { tags: always }
  tags: install-develop-grep

- name: Install package group "install-develop-image"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-image
    apply: { tags: always }
  tags: install-develop-image

- name: Install package group "install-develop-lang"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-lang
    apply: { tags: always }
  tags: install-develop-lang

- name: Install package group "install-develop-misc"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-misc
    apply: { tags: always }
  tags: install-develop-misc

- name: Install package group "install-develop-net"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-net
    apply: { tags: always }
  tags: install-develop-net

- name: Install package group "install-develop-net-wireshark"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-net-wireshark
    apply: { tags: always }
  tags: install-develop-net-wireshark
  # USAGE: OPTIN: Use explicit tags to run this task:
  #   ansible-playbook ... --tags install-develop-net-wireshark ...
  when: "'install-develop-net-wireshark' in ansible_run_tags"

- name: Install package group "install-develop-perl"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-perl
    apply: { tags: always }
  tags: install-develop-perl

- name: Install package group "install-develop-python"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-python
    apply: { tags: always }
  tags: install-develop-python

- name: Install package group "install-develop-ruby"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-ruby
    apply: { tags: always }
  tags: install-develop-ruby

- name: Install package group "install-develop-sec"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-sec
    apply: { tags: always }
  tags: install-develop-sec

- name: Install package group "install-develop-spatial"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-spatial
    apply: { tags: always }
  tags: install-develop-spatial

- name: Install package group "install-develop-terminal"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-terminal
    apply: { tags: always }
  tags: install-develop-terminal

- name: Install package group "install-develop-text"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-text
    apply: { tags: always }
  tags: install-develop-text

- name: Install package group "install-develop-vcs"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-vcs
    apply: { tags: always }
  tags: install-develop-vcs

- name: Install package group "install-develop-vim"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-vim
    apply: { tags: always }
  tags: install-develop-vim

- name: Install package group "install-develop-web"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-develop-web
    apply: { tags: always }
  tags: install-develop-web

# ******************************************************
# *** "Base" Debian packages (potentially distro-version-specific)
#
# — This is a minimal set of packages author needs to onboard new Debian 12 host.
#
# - Packages installed by this task are duplicates of packages installed by the
#   other tasks.

- name: Install package group "install-base-debian"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-base-debian
    apply: { tags: always }
  tags: install-base-debian
  # USAGE: OPTIN: Use explicit tags to run this task:
  #   ansible-playbook ... --tags install-base-debian ...
  when: >
    'install-base-debian' in ansible_run_tags and (
      ansible_lsb.id == 'Debian' and ansible_lsb.major_release|int >= 12
    )

# ******************************************************
# *** Flatpaks

- name: Install package group "install-flatpaks"
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-flatpaks
    apply: { tags: always }
  tags: install-flatpaks
  when: ansible_lsb.id == 'LinuxMint'

- name: Load tasks to create flatpak update timer task
  ansible.builtin.include_role:
    name: zoidy_captivator
    tasks_from: install-flatpaks-automatic-updates
    apply: { tags: always }
  tags: install-flatpaks-automatic-updates
  when: ansible_lsb.id == 'LinuxMint'

