---

# *** Update package list, and upgrade installed packages.

- name: Update and upgrade installed packages
  include_role:
    name: zoidy_mintyfresh
    tasks_from: update-upgrade
  tags: update-upgrade, update, upgrade

# *** Install build essentials.

- name: Install package group "build essentials"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-build-essentials
  tags: install-build-essentials

# *** Install new packages, grouped by functionality.

# 2023-03-24: I haven't worked with MP3 files or audio apps in a while,
# so opt-in now.
#
# - name: Install package group "install-desktop-abcde"
#   include_role:
#     name: zoidy_mintyfresh
#     tasks_from: install-desktop-abcde
#   tags: install-desktop-abcde
#
# - name: Install package group "install-desktop-audio"
#   include_role:
#     name: zoidy_mintyfresh
#     tasks_from: install-desktop-audio
#   tags: install-desktop-audio

- name: Install package group "install-desktop-core"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-core
  tags: install-desktop-core

- name: Install package group "install-desktop-docs"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-docs
  tags: install-desktop-docs

- name: Install package group "install-desktop-email"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-email
  tags: install-desktop-email

- name: Install package group "install-desktop-font"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-font
  tags: install-desktop-font

- name: Install package group "install-desktop-image"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-desktop-image
  tags: install-desktop-image

- name: Install package group "install-develop-android"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-android
  tags: install-develop-android

- name: Install package group "install-develop-dbms"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-dbms
  tags: install-develop-dbms

- name: Install package group "install-develop-fortunes"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-fortunes
  tags: install-develop-fortunes

- name: Install package group "install-develop-grep"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-grep
  tags: install-develop-grep

- name: Install package group "install-develop-image"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-image
  tags: install-develop-image

- name: Install package group "install-develop-lang"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-lang
  tags: install-develop-lang

- name: Install package group "install-develop-misc"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-misc
  tags: install-develop-misc

- name: Install package group "install-develop-net"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-net
  tags: install-develop-net, install-develop-net-wireshark

- name: Install package group "install-develop-perl"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-perl
  tags: install-develop-perl

- name: Install package group "install-develop-python"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-python
  tags: install-develop-python

- name: Install package group "install-develop-ruby"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-ruby
  tags: install-develop-ruby

- name: Install package group "install-develop-sec"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-sec
  tags: install-develop-sec

- name: Install package group "install-develop-spatial"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-spatial
  tags: install-develop-spatial

- name: Install package group "install-develop-terminal"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-terminal
  tags: install-develop-terminal

- name: Install package group "install-develop-text"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-text
  tags: install-develop-text

- name: Install package group "install-develop-vcs"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-vcs
  tags: install-develop-vcs

- name: Install package group "install-develop-vim"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-vim
  tags: install-develop-vim

- name: Install package group "install-develop-web"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-develop-web
  tags: install-develop-web

# *** Install new packages for specific distributions.

- name: Install package group "install-distro-14.04"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-14.04
  tags: install-distro-14.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 17

- name: Install package group "install-distro-16.04"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-16.04
  tags: install-distro-16.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 18

- name: Install package group "install-distro-18.04"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-18.04
  tags: install-distro-18.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 19

- name: Install package group "install-distro-22.04"
  include_role:
    name: zoidy_mintyfresh
    tasks_from: install-distro-22.04
  tags: install-distro-22.04
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 21

# *** Perform sudo setup operations (I'm too lazy to put in other Galaxy Role).

- name: Determine if host is “Desktop” or “Laptop”
  # (lb): Response should be either "Desktop" or "Notebook", at least what I've seen.
  ansible.builtin.shell: dmidecode --string chassis-type
  become: yes
  register: chassis_type
  tags: laptop-lid-disable-wake-on

- name: Load role to Deactivate Reactive Laptop Lid Response
  include_role:
    name: zoidy_mintyfresh
    tasks_from: laptop-lid-disable-wake-on
    apply:
      tags:
        - laptop-lid-disable-wake-on
  tags: laptop-lid-disable-wake-on
  when: chassis_type.stdout == 'Notebook'

# ***

- name: Load role to Lock Sessions on Power Suspend
  include_role:
    name: zoidy_mintyfresh
    tasks_from: power-suspend-lock-sessions
    apply:
      tags:
        - power-suspend-lock-sessions
  tags: power-suspend-lock-sessions

- name: Load role to Customize Log on Greeter Screen Background
  include_role:
    name: zoidy_mintyfresh
    tasks_from: log-on-screen-background
    apply:
      tags:
        - log-on-screen-background
  tags: log-on-screen-background

# ***

# - name: Load role to Install Systemwide Pips
#   include_role:
#     name: zoidy_mintyfresh
#     tasks_from: pippin-out
#     apply:
#       tags:
#         - pippin-out
#   tags: pippin-out

# ***

# - name: Load role to Install Ubuntu Snaps
#   include_role:
#     name: zoidy_mintyfresh
#     tasks_from: ubuntu-snaps
#     apply:
#       tags:
#         - ubuntu-snaps
#   tags: ubuntu-snaps

