---

- name: 'Install spatial packages'
  become: true
  apt: name={{ item }}
  loop:

    # Cartographic projection packages.
    # libproj-dev - Cartographic projection library (development files)
    - libproj-dev
    # proj-bin - Cartographic projection library (tools)
    - proj-bin
    # proj-data - Cartographic projection filter and library (datum package)
    - proj-data

    # ogrinfo et al.
    # gdal-bin - Geospatial Data Abstraction Library - Utility programs
    # node-srs - spatial reference library for Node.js
    - gdal-bin

    # gpx2shp missing in 22.04.
    # - Package page last updated 2014, so might no longer be supported
    #     https://gpx2shp.osdn.jp/
    # - Or might have been rolled into `gis-gps` (but doubt it).
    # Circa Ubuntu 18.04:
    #   # gpx2shp - convert GPS or GPX file to ESRI Shape file
    #   - gpx2shp

