---

# dkms: Dynamic Kernel Module Support Framework

- name: Install essential build essentials
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    # Kernel goodies.
    - dkms
    - build-essential

