---

- name: 'Install Vim and related packages'
  become: true
  apt: name={{ item }}
  loop:

    # Vim. (See elsewhere: Install Dubs Vim.)
    # Flavors: vim-gtk, vim-gtk3, vim-tiny
    # (lb): Note that ZP builds Vim from scratch (see
    # app-vim-brams.yml) but we want to install vim-gtk
    # so that /usr/bin/vim is created (and then, e.g.,
    # running `vim` will work from the root account).
    - vim-gtk

    # TRYIT/2023-03-24: Someday I'll demo neovim...
    - neovim

    # Text columnizer. (Replaced by custom fork: parT)
    #   #- par

    # Ctags.
    - exuberant-ctags

    # Ruby dev tools for Command-T.
    - ruby-dev

    # Libraries needed to build Vim. See also:
    #   sudo apt-get -s build-dep vim
    # (provided you have update sources.list,
    #  which these Zoidy Pooh Ansible Roles do not).

    - libncurses5-dev
    # ncursesw is ncurses with Unicode (wide character) support.
    - libncursesw5-dev

    # For GUI support. Without it, Vim builds, but gvim symlink
    # is not made (and if you make it and run it, complains:
    #   $ gvim
    #   E25: GUI cannot be used: Not enabled at compile time
    - libgtk2.0-dev

