---

- name: 'Install security packages'
  become: true
  apt: name={{ item }}
  tags: install-develop-sec
  loop:

    # EncFS is the classic encrypted filesystem.
    # See also: CryFS, and gocryptfs.
    - encfs

    # 2018-09-20: New hotness.
    - cryfs

    # You shouldn't need to scrub if your sensitive bits only
    # hit metal through encrypted file systems, but nevertheless.
    - scrub

    # FIXME/2018-12-15: [lb]: Disable for now -- I'm curious how `pass` works without.
    #- pinentry-gtk2
    #- pinentry-doc

    # gnupg - GNU privacy guard - a free PGP replacement
    # gnupg1 - GNU privacy guard - a PGP implementation (deprecated "classic" version)
    # gnupg2 - GNU privacy guard - a free PGP replacement (dummy transitional package)
    - gnupg2

    - pwgen

    # libpam0g - Pluggable Authentication Modules library
    # libpam0g-dev - Development files for PAM
    - libpam0g-dev

    # 2020-04-12: For building git.
    - libssl-dev

    # NOTE: OpenSSH likely installed, because you did so to run Zoidy Ansible!
    - openssh-server

    # At least they didn't name it signing-key-party.
    - signing-party

    # [lb]: keepassx may work for some people, but I'm smitten with `pass`.
    #   - keepassx
    # FIXME/2018-12-17: I built pass previously. Do I still need to?
    - pass

    - tomb
    # Optional extensions. Run `tomb --version`
    - dcfldd
    - steghide
    #  tomb-kdb-pbkdf2: cannot find
    #  For similar:
    #     apt-cache search pbk
    #- tomb-kdb-pbkdf2
    - qrencode
    - swish-e
    - unoconv

    # 2019-03-14: It lags:
    #   $ gocryptfs -version
    #   gocryptfs 1.4.3; go-fuse 0.0~git20171124.0.14c3015; 2018-02-05 go1.9.3
    # Be hardened, and install from GitHub release instead.
    #   - gocryptfs

# https://en.wikipedia.org/wiki/Filesystem_in_Userspace
- name: 'Add user to fuse group'
  become: true
  tags: install-develop-sec
  user:
    name: "{{ ansible_env.LOGNAME }}"
    groups: fuse
    append: yes
  # FIXME/2018-12-15: On 18.04, no fuse group. I guess if encfs works,
  # I don't care! (Otherwise, maybe I'm missing a step.)
  when: False

