---

- name: "Install core desktop tools"
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # CLI OS and Window Manager customizers.
    - dconf-cli

    # These are essential on MATE (Linux Mint), but still work (to
    # some extent) on GNOME Shell (Debian).
    - wmctrl
    - xdotool

    # apt-file - search for files within Debian packages (command-line interface)
    - apt-file

    # "detect if we are running in a virtual machine"
    #  - virt-what

    # Bleeding edge Chrome.
    - chromium-browser

    # Eye of Gnome, a slideshow image viewer.
    # - Installed by default on Debian 12.
    - eog

    # [meld is the] Awesomest graphical diff.
    # 2020-02-04: Avoid the distro's meld, currently stuck at 3.18.0.
    #   It has at least one known, annoying issue: If you close a comparison
    #   before saving, you're prompted to save changes, but no matter how
    #   you respond, the comparison stays open, and the Ctrl-w close command
    #   no longer works to close it, and you have to click the 'x' button).
    #   * See replacement task:
    #     zoidy_apps_et_al/tasks/app-meld.yml
    # - meld

    # Hexadecimal file viewer.
    - ghex

    - hexedit

    # Hexadecimal diff.
    # [lb] I use ghex very rarely, and vbindiff less so,
    # but a hex viewer and a differ are essential tools.
    - vbindiff
    # Meh on hexdiff.
    #  - hexdiff

    # Color pickers.
    # - HSTRY/2018-12-15: Previously used gcolor2.
    #   - REFER: Some tips from people asking for alts:
    #       zenity --color-selection
    #       yad --color  # Like zenity, but not installed by default
    #       gpick
    #     https://askubuntu.com/questions/1073990/gcolor2-package-missing-in-ubuntu-18-04
    #   - NOTED: "gcolor3 does not have broad list of predefined colors".
    #
    # REFER: https://gitlab.gnome.org/World/gcolor3
    # "Simple GTK3 color selector and picker"
    - gcolor3
    # "advanced GTK+ color picker"
    - gpick

    # artha - "Handy off-line thesaurus based on WordNet"
    # HINT: After running, press Ctrl-Alt-W to foreground!
    # [lb]: I don't really use this, but like to know that
    # if I'm offline, I can find a dictionary & thesaurus.
    - artha

    # Let users mount devices (i.e., and avoid having to use `caja` GUI).
    - pmount

