---

- name: 'Install miscellaneously-categoried development applications'
  become: true
  apt: name={{ item }}
  loop:

    # 2022-01-31: dateutils.ddiff
    - dateutils

    # 2020-02-12: `fd` find alternative, available in Ubuntu 19.04+.
    # - If you need to install from deb, identify latest release:
    #     sensible-browser https://github.com/sharkdp/fd/releases
    #   Then run, e.g.,:
    #     cd ~/.downloads
    #     wget https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb
    #     sudo dpkg -i fd_7.4.0_amd64.deb
    - fd-find

    - fdupes

    # feedgnuplot - Pipe-oriented frontend to Gnuplot
    # 2021-09-20: As seen used in Git rev-list histogram example:
    #   https://github.blog/2021-08-16-highlights-from-git-2-33/
    - feedgnuplot

    - htop

    - jq

    - logcheck
    - logcheck-database

    - lzip

    # mount.nfs
    - nfs-common

    # nslookup is... stale, to be polite. Use `dig` instead.

    # Un-Zip-a-Dee-Doo-Dah
    - unzip

    - tree

    # ScreenRuler project page:
    #
    #   https://gnomecoder.wordpress.com/screenruler/
    #
    # ScreenRulers source:
    #
    #   https://code.launchpad.net/screenruler
    - screenruler

