---

- name: 'Install Photo/Graphics Management/Viewing applications'
  become: true
  apt: name={{ item }}
  tags: install-desktop-photo
  loop:

    # Webcam software.
    #  https://help.ubuntu.com/community/Webcam
    # cheese - tool to take pictures and videos from your webcam
    - cheese

    # gthumb - image viewer and browser
    - gthumb

    # Install digikam from AppImage, as the distro version lags with bugs.
    #   #- digikam
    # 2018-12-15: [lb] Still install docs? Are they even current?
    #   #- digikam-doc
    # For reference, packages that have been needed for digikam [~ 1 GB?].
    #   #- kde-full
    #   - cmake
    #   - qt4-qmake
    #   - qt5-qmake
    #   - kdevplatform-dev
    #   # Color mgmt.
    #   - gnome-color-manager
    #   #- dispcalgui

    # Shotwell personal photo manager.
    #   http://shotwell-project.org/doc/html/
    # FIXME/2018-12-15: [lb]: I still have not used `shotwell`!
    # shotwell - digital photo organizer
    - shotwell

