---

- name: 'Install terminal tools'
  become: true
  apt: name={{ item }}
  tags: install-develop-terminal
  loop:

    # tmux - terminal multiplexer
    - tmux

    # xclip - command line interface to X selections
    - xclip

    # *** Shell

    # expect - Automates interactive applications
    - expect

    # 2018-12-14: Is this needed for some Home Fries functionality?
    # libedit-dev - BSD editline and history libraries (development files)
    # FIXME/2018-12-14 18:55: Disabling for now! Revisit.
    #- libedit-dev

    # inotify-tools - command-line programs providing a simple interface to inotify
    - inotify-tools

    # Try mosh, as suggested by wonderful post of using Ansible to secure a
    # linux box (which I found while looking for task to regex sshd_config).
    #   https://ryaneschinger.com/blog/securing-a-server-with-ansible/
    # mosh - Mobile shell that supports roaming and intelligent local echo
    - mosh

    # [lb] Maybe someday I'll try a shell other than Bash.
    #  (But why rock the boat when you've got a good thing?)
    # zsh - shell with lots of features
    - zsh

