---

- name: 'Install security packages'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # EncFS is the classic encrypted filesystem.
    # See also: CryFS, and gocryptfs.
    - encfs

    # 2018-09-20: New hotness.
    # - ORNOT/2025-10-28: I don't currently use cryfs, though
    #   I do respect its filesystem and block size obsfucation.
    - cryfs

    # You shouldn't need to scrub if your sensitive bits only
    # hit metal through encrypted file systems, but nevertheless.
    - scrub

    # gnupg - GNU privacy guard - a free PGP replacement
    - gnupg

    - pwgen

    # libpam0g - Pluggable Authentication Modules library
    # libpam0g-dev - Development files for PAM
    - libpam0g-dev

    # 2020-04-12: For building git.
    - libssl-dev

    # SAVVY: OpenSSH likely installed, because you did so to run Ansible tasks!
    - openssh-server

    # At least they didn't name it signing-key-party. [mic drop?]
    - signing-party

    # AWARE/2025-10-28: Author builds a `pass` fork (that adds Neovim syntax
    # highlighting), so this command (/usr/bin/pass) will be shadowed by the
    # custom build (~/.local/bin/pass).
    # - This'll work before the custom build created (or serve as a fallback).
    # - REFER/2018-12-17: KeePassX [now KeePassXC] is another popular choice:
    #   https://keepassxc.org/
    - pass

    - tomb
    # Optional extensions. Run `tomb --version`
    # - dcfldd — enhanced version of dd for forensics and security
    - dcfldd
    - steghide
    #  tomb-kdb-pbkdf2: cannot find
    #  For similar:
    #     apt-cache search pbk
    #- tomb-kdb-pbkdf2
    - qrencode
    - swish-e
    - unoconv

    # Skip distro gocryptfs:
    #  - gocryptfs
    # and install from GitHub release instead.
    #
    # - 2019-03-14: Linux Mint 19.3:
    #   $ gocryptfs -version
    #   gocryptfs 1.4.3; go-fuse 0.0~git20171124.0.14c3015; 2018-02-05 go1.9.3
    # - 2023-04-11: Linux Mint 21.1:
    #   $ gocryptfs -version
    #   gocryptfs 1.8.0; go-fuse 2.0.3; 2021-11-23 go1.17.3 linux/amd64
    #   - 1.8.0 is last v1 release.
    # - GH latest: v2.3.1
    #     https://github.com/rfjakob/gocryptfs/releases
    # - What I've been running from sources:
    #   $ gocryptfs -version
    #   gocryptfs v2.3.1 without_openssl; go-fuse v2.1.1-0.20221117175120-915cf5413cde; 2023-03-04 go1.19.6 linux/amd64

# https://en.wikipedia.org/wiki/Filesystem_in_Userspace
- name: 'Add user to fuse group'
  become: true
  user:
    name: "{{ ansible_env.LOGNAME }}"
    groups: fuse
    append: yes
  # FIXME/2018-12-15: On 18.04, no fuse group. I guess if encfs works,
  # I don't care! (Otherwise, maybe I'm missing a step.)
  when: False

