---

- name: 'Install Android development app(s)'
  become: true
  apt: name={{ item }}
  tags: install-develop-android
  loop:

    # 2016-09-30: Weird. I swore this was already part of setup.
    # 2016-10-03: I installed adb first, then android-tools-adb,
    # and the latter uninstalled the former. Hmmm.
    #   - adb
    - android-tools-adb

