---

- name: 'Install emailing, messaging, and related packages'
  become: true
  apt: name={{ item }}
  tags: install-desktop-email
  loop:

    - thunderbird
    # Mutt bark bark better than mail (see also: elm).
    - mutt

    - mime-construct

    # For getting at automated emails sent by daemons.
    #   - mail
    #   - mutt
    #   #- mutt-patched
    #   - alpine
    # You can also just do:
    #  sudo cat /var/spool/mail/root
    #  sudo tail -n 1000 /var/spool/mail/root
    #  sudo grep "cron" /var/spool/mail/root

    # akregator - RSS/Atom feed aggregator
    - akregator

