---

- name: 'Install cowsay and fortune packages'
  become: true
  apt: name={{ item }}
  tags: install-develop-fortunes
  loop:

    # *** cowsay

    # 2019-01-23: Mainly for git-committing dob plugin,
    #   ~/.config/dob/plugins/my_post_processor.py
    # cowsay - configurable talking cow
    - cowsay
    # cowsay-off - configurable talking cow (offensive cows)
    - cowsay-off
    # 2019-01-23: Saw this, too, but did not bother investigating what'is.
    # xcowsay - Graphical configurable talking cow
    # - xcowsay

    # *** fortune

    # fortune-mod - provides fortune cookies on demand
    - fortune-mod
    # fortunes - Data files containing fortune cookies
    # 2019-01-23: I removed fortunes, and /usr/share/games/fortunes
    #   still has: fortunes, literature, and riddles.
    - fortunes
    # Other fortune lists you'll find on `apt-cache search fortune`:
    # - fortunes-min - Data files containing selected fortune cookies
    #   - fortunes-min is just a subset of fortunes, looks like.
    # - fortunes-off - Data files containing offensive fortune cookies
    #   - `fortune -o`. Meh. Or, `fortune -a` to choose between off, and not.
    #     Not that clever. And I really just need noise, not something read.
    # - fortunes-bofh-excuses - BOFH excuses for fortune
    #   - From a time before cloud. Golden oldies such as:
    #       BOFH excuse #364:
    #       Sand fleas eating the Internet cables
    # - fortune-anarchism - anarchist quotes for fortune
    #   - `fortune anarchism`, if you want to leave America for a spell, e.g.,
    #       Order results spontaneously when things are let alone.
    #       ----+- Zhuangzi -+----
    - fortune-anarchism
    # - display-dhammapada - fortune-like collection of Buddhist sayings
    #   - Its own app, `display-dhammapada`; not sure where its files.

