---

- name: 'Install Android development app(s)'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # HSTRY/2025-01-15: Previously installed 'android-tools-adb'
    # but that was a transitional package.
    # "Android Debug Bridge"
    - adb

