---

- name: 'Install network app development, diagnostic, and security tools'
  become: true
  ansible.builtin.apt: name={{ item }}
  tags: install-develop-net
  loop:

    - curl

    - wget

    - rsync

    - sshfs

    - traceroute

    - whois

    # *** Terminal-based Wireshark alternatives.

    # ssldump - SSLv3/TLS network protocol analyzer
    - ssldump

    # tshark - network traffic analyzer - console version
    - tshark

    - nmap

    - ufw

    # *** Email

    # mailutils - includes 9 commands, including `mail`.
    #   https://packages.debian.org/search?keywords=mailutils
    #   https://packages.debian.org/trixie/mailutils
    - mailutils

    # postfix - Wietse Venema's mail transport agent (alt. to Sendmail).
    #   https://packages.debian.org/search?keywords=postfix
    #   https://packages.debian.org/trixie/postfix
    # CXREF: Because interactive and non-trivial setup,
    # see postfix install task from other Ansible playbook:
    #   https://github.com/landonb/zoidy_apps_et_al 🦞
    #     ~/.kit/ansible/roles/zoidy_apps_et_al/tasks/email-gmail-postfix.yml
    #  - postfix

    # See also Dovecot, open source IMAP and POP3 mail server:
    #   https://packages.debian.org/search?keywords=dovecot
    #   https://packages.debian.org/trixie/dovecot-core
    # REFER:
    #   https://doc.dovecot.org/latest/
    #   https://wiki.archlinux.org/title/Dovecot
    # Author only needs to forward emails to external service, so
    # doesn't need mail server, but here's how you might set it up:
    #   https://www.linode.com/docs/guides/email-with-postfix-dovecot-and-mysql/

- name: 'Install network app development, diagnostic, and security tools (Debian)'
  when: ansible_lsb.id == 'Debian'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    # `nslookup`
    - bind9-dnsutils

- name: 'Install network app development, diagnostic, and security tools (Linux Mint)'
  when: ansible_lsb.id == 'LinuxMint'
  become: true
  ansible.builtin.apt: name={{ item }}
  tags: install-develop-net
  loop:
    # `nslookup`
    - dnsutils

    # 2025-01-15: Not found in Debian 12 sources.
    - socket

