---

- name: 'Install assorted development and sysadmin apps'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # 2022-01-31: dateutils.ddiff
    - dateutils

    # 2020-02-12: `fd` find alternative, available in Ubuntu 19.04+.
    # - If you need to install from deb, identify latest release:
    #     sensible-browser https://github.com/sharkdp/fd/releases
    #   Then run, e.g.,:
    #     cd ~/.downloads
    #     wget https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb
    #     sudo dpkg -i fd_7.4.0_amd64.deb
    # - Note this was 'fd' package on LM 19.3.
    - fd-find

    - fdupes

    # feedgnuplot - Pipe-oriented frontend to Gnuplot
    # 2021-09-20: As seen used in Git rev-list histogram example:
    #   https://github.blog/2021-08-16-highlights-from-git-2-33/
    - feedgnuplot

    - logcheck
    - logcheck-database

    - lzip

    # /sbin/mount.nfs, /sbin/mount.nfs4
    - nfs-common

    # nslookup is... stale, to be polite. Use `dig` instead.

    # `locate` command (formerly mlocate; see also Homebrew glocate
    # from findutils (though not in APT findutils)).
    - plocate

    # ScreenRuler project page:
    #
    #   https://gnomecoder.wordpress.com/screenruler/
    #
    # ScreenRulers source:
    #
    #   https://code.launchpad.net/screenruler
    - screenruler

    - tree

    # Un-Zip-a-Dee-Doo-Dah
    - unzip

- name: 'Install resource monitoring apps (*top)'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # "Resource monitor that shows usage and stats"
    - bpytop
    # "Modern and colorful command line resource monitor that shows usage and stats"
    - btop

    - htop

    # Network activity monitor, like `top`. Requires sudo.
    - iftop

- name: 'Install assorted development and sysadmin apps (Mint-only)'
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int >= 21
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # 2023-05-03: bashtop, `htop` alternative; see also: `glances`.
    # - 2025-01-15: Not found in Debian 12 or LM 19.3 sources.
    - bashtop

