---

- name: 'Install network app development, diagnostic, and security tools'
  become: true
  ansible.builtin.apt: name={{ item }}
  tags: install-develop-net
  loop:

    - curl

    - wget

    - rsync

    - sshfs

    - traceroute

    - whois

    # *** Terminal-based Wireshark alternatives.

    # ssldump - SSLv3/TLS network protocol analyzer
    - ssldump

    # tshark - network traffic analyzer - console version
    - tshark

    - nmap

    - ufw

- name: 'Install network app development, diagnostic, and security tools (Debian)'
  when: ansible_lsb.id == 'Debian'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    # `nslookup`
    - bind9-dnsutils

- name: 'Install network app development, diagnostic, and security tools (Linux Mint)'
  when: ansible_lsb.id == 'LinuxMint'
  become: true
  ansible.builtin.apt: name={{ item }}
  tags: install-develop-net
  loop:
    # `nslookup`
    - dnsutils

    # 2025-01-15: Not found in Debian 12 sources.
    - socket

