---

- name: Install essential build essentials
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    # Dynamic Kernel Module System (DKMS)
    - dkms
    # Collection of build tools
    - build-essential

