---

- name: 'Install terminal tools'
  become: true
  apt: name={{ item }}
  tags: install-develop-terminal
  loop:

    # tmux - terminal multiplexer
    - tmux

    # terminator - multiple GNOME terminals in one window
    - terminator
    # Avoid warnings, e.g.,
    #
    #   $ terminator -l <layout>
    #   Unable to load Keybinder module. This means the hide_window shortcut will be unavailable
    #   Unable to bind hide_window key, another instance/window has it.
    #
    # by installing recommended packages. Per package description:
    #
    #   $ apt-cache show terminator
    #   Version: 1.91-1
    #   Depends: python-cairo, ...
    #   Recommends: gir1.2-keybinder-3.0, gir1.2-notify-0.7, xdg-utils
    #
    # [lb]: With additional packages, I see one remaining warning, but whatever; e.g.,:
    #
    #   <window.Window object at 0x7f385ab506e0 (terminatorlib+window+Window at 0x55768b192290)>
    #     is not in registered window list
    #
    # gir1.2-keybinder-3.0 - registers global key bindings for applications - Gtk+3 - typelib
    # gir1.2-notify-0.7 - sends desktop notifications to a notification daemon (Introspection files)
    # xdg-utils - desktop integration utilities from freedesktop.org
    - gir1.2-keybinder-3.0
    - gir1.2-notify-0.7
    - xdg-utils

    # xclip - command line interface to X selections
    - xclip

    # *** Shell

    # expect - Automates interactive applications
    - expect

    # 2018-12-14: Is this needed for some Home Fries functionality?
    # libedit-dev - BSD editline and history libraries (development files)
    # FIXME/2018-12-14 18:55: Disabling for now! Revisit.
    #- libedit-dev

    # inotify-tools - command-line programs providing a simple interface to inotify
    - inotify-tools

    # Try mosh, as suggested by wonderful post of using Ansible to secure a
    # linux box (which I found while looking for task to regex sshd_config).
    #   https://ryaneschinger.com/blog/securing-a-server-with-ansible/
    # mosh - Mobile shell that supports roaming and intelligent local echo
    - mosh

    # Progress meter.
    # pv - Shell pipeline element to meter data passing through
    - pv

    # [lb] Maybe someday I'll try a shell other than Bash.
    #  (But why rock the boat when you've got a good thing?)
    # zsh - shell with lots of features
    - zsh

