---

- name: 'Install desktop apps — misc (Mint-only)'
  when: ansible_lsb.id == 'LinuxMint'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # "lets you dock any application into the system tray"
    - kdocker

    # Installs `notify-send` desktop notifications app.
    # - HSTRY/2025-01-16: This is a dependency of one or more other
    #   packages installed by zoidy_mintyfresh on Debian 12. I.e.,
    #   it'll be installed whether listed here or not if you play
    #   the full role.
    - libnotify-bin

    # "utility for tracking non-official package versions"
    # - No obviously value-add because apt-list does same,
    #   e.g.:
    #
    #   $ apt list '?narrow(?installed, ?not(?origin(Debian)))'
    #   google-chrome-stable/stable,now 140.0.7339.127-1 amd64 [installed]
    #   interactive-rebase-tool/now 2.4.1-1 amd64 [installed,local]
    #   spotify-client/stable,now 1:1.2.63.394.g126b0d89 amd64 [installed]
    #
    #   $ apt-forktracer | sort
    #   google-chrome-stable (140.0.7339.127-1) [Google LLC: 140.0.7339.127-1]
    #   interactive-rebase-tool (2.4.1-1)
    #   spotify-client (1:1.2.63.394.g126b0d89) [Spotify LTD: 1:1.2.63.394.g126b0d89]
    - apt-forktracer
