---

- name: 'Install grepper packages (not including `rg`)'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # [lb]: I don't personally use ack, but sometimes I copy-paste it.
    # "grep-like program specifically for large source trees"
    - ack

    # For when you need Perl-style regex.
    # pcregrep - grep utility that uses perl 5 compatible regexes.
    # - CXREF: Used by:
    #   - Vim modeline plugin
    #     ~/.vim/pack/landonb/start/dubs_style_guard/plugin/dubs_style_guard.vim
    #   - OMR 'install' task:
    #       mr -d ~/.kit/git/tig -n install
    #     ~/.depoxy/ambers/home/.kit/git/_mrconfig-git-core
    - pcregrep

    # ripgrep is the fastest searcher! > ag > grep
    # - 2024-02-06: Linux Mint 21.3 includes ripgrep 13.0.0
    # - REFER: For the latest ripgrep (curr. 14.1.0), see:
    #     https://github.com/landonb/zoidy_apps_et_al
    #   CXREF: On a DepoXy install, located at:
    #     ~/.kit/ansible/roles/zoidy_apps_et_al/tasks/cli-ripgrep.yml
    - ripgrep

    # The stately Silver Search, ag.
    - silversearcher-ag

