---

# CXREF/2022-10-01:
#
#   https://flatpak.org/setup/Ubuntu
#
#   https://flathub.org/apps/details/org.gnome.meld
#   https://flathub.org/apps/details/org.gimp.GIMP
#
#   https://docs.ansible.com/ansible/latest/collections/community/general/flatpak_module.html
#   https://docs.ansible.com/ansible/latest/collections/community/general/flatpak_remote_module.html

# ***

# SAVVY/2023-04-20 19:42: If you don't remote-add before install, it'll error, e.g.,
#  error: No remote refs found similar to ‘flathub’
# Runs, e.g.,
#   flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
- name: Add the Flathub Flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

# ***

# Install meld, e.g.,
#   flatpak install flathub org.gnome.meld
# SAVVY: Run it:
#   flatpak run org.gnome.meld
# SPEED/2023-04-20 19:51: Slow. At least on Lenovo X201 Wi-Fi, 8m42s.
- name: Install the meld Flatpak
  community.general.flatpak:
    name: org.gnome.meld
    state: present
    method: user

# ***

# Install GIMP, e.g.,
#   flatpak install flathub org.gimp.GIMP
# ALTLY: You could download it and install from local file: CXREF:
#   https://dl.flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
# SPEED/2023-04-20 20:02: Slow. At least on Lenovo X201 Wi-Fi, 5m26s.
- name: Install the GIMP Flatpak
  community.general.flatpak:
    name: org.gimp.GIMP
    state: present
    method: user

# CXREF/2023-04-23: The GIMP desktop file:
#   ~/.local/share/flatpak/app/org.gimp.GIMP/current/active/files/share/applications/org.gimp.GIMP.desktop
# calls `gimp-2.10`, which I guess we need to create ourselves (or edit the desktop file).
# - CXREF: ~/.kit/ansible/roles/zoidy_panelsweet/defaults/main/panel-objects.yml
# - DUNNO: I'm not sure if launchers search ~/.local/bin directly,
#   or if the launcher PATH is coming from my ~/.profile or something.
- name: Creating GIMP ~/.local/bin alias
  ansible.builtin.copy:
    dest: ~/.local/bin/gimp-2.10
    content: |
      #!/bin/bash
      flatpak run org.gimp.GIMP
    mode: 0755

# ***

# Install Slack, e.g.,
#   flatpak install flathub com.slack.Slack -y
# SAVVY: Run it:
#   flatpak run com.slack.Slack
# DUNNO/2024-02-13: Slack Flatpak installs a Desktop file, e.g.,
#   ~/.local/share/flatpak/app/com.slack.Slack/current/active/files/share/applications/com.slack.Slack.desktop
# But it simply runs `com.slack.Slack`. You'll see a local bin at, e.g.,
#   ~/.local/share/flatpak/app/com.slack.Slack/current/active/files/bin/com.slack.Slack
# But this executable calls zypak-wrapper, which is a broken symlink, e.g.,
#   ~/.local/share/flatpak/app/com.slack.Slack/current/active/files/bin/zypak-wrapper
#     -> /app/bin/zypak-wrapper.sh
# And searching doesn't indicate that end users are meant to install Zypak, REFER:
#   https://github.com/refi64/zypak
# Additionally, the Slack Flatpak itself says to run it like any other Flakpak, e.g.,
#   flatpak run com.slack.Slack
# REFER:
#   https://github.com/flathub/com.slack.Slack/blob/master/README.md
- name: Install the Slack Flatpak
  community.general.flatpak:
    name: com.slack.Slack
    state: present
    method: user

