---

- name: "Install core desktop tools"
  become: true
  apt: name={{ item }}
  tags: install-desktop-core
  loop:

    # CLI OS and Window Manager customizers.
    - dconf-cli
    - gconf-editor
    - wmctrl
    - xdotool

    # apt-file - search for files within Debian packages (command-line interface)
    - apt-file

    # Are we in a virtual machine?
    #  - virt-what

    # Bleeding edge Chrome.
    - chromium-browser

    # Eye of Gnome, a slideshow image viewer.
    - eog

    # [meld is the] Awesomest graphical diff.
    # 2020-02-04: Avoid the distro's meld, currently stuck at 3.18.0.
    #   It has at least one known, annoying issue: If you close a comparison
    #   before saving, you're prompted to save changes, but no matter how
    #   you respond, the comparison stays open, and the Ctrl-w close command
    #   no longer works to close it, and you have to click the 'x' button).
    #   * See replacement task:
    #     zoidy_home-fries/tasks/app-meld.yml
    # - meld

    # Hexadecimal file viewer.
    - ghex

    - hexedit

    # Hexadecimal diff.
    # [lb] I use ghex very rarely, and vbindiff less so,
    # but a hex viewer and a differ are essential tools.
    - vbindiff
    # Meh on hexdiff.
    #  - hexdiff

    # Color picker.
    # FIXME/2018-12-15: gcolor2 is missing from 18.04.
    #- gcolor2
    #   https://askubuntu.com/questions/1073990/gcolor2-package-missing-in-ubuntu-18-04
    # Maybe wire deb installer, e.g.,
    #   cd ~/Downloads
    #   wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcolor2/gcolor2_0.4-2.1ubuntu1_amd64.deb
    #   sudo apt-get install ./gcolor2_0.4-2.1ubuntu1_amd64.deb
    # or Maybe update to gcolor3
    #   ppa:evertiro/gcolor3
    # except "gcolor3 does not have broad list of predefined colors".
    # Which is probably a feature, not a bug, because predefined colors
    # clutter a list of colors shared with user-saved colors. Ahuh.

    # artha - Handy off-line thesaurus based on WordNet
    # HINT: After running, press Ctrl-Alt-W to foreground!
    # [lb]: I don't really use this, but like to know that
    # if I'm offline, I can find a dictionary & thesaurus.
    - artha

    # [lb] Because I disabled the screensaver lock, need manual method.
    # gnome-screensaver-command --lock
    - gnome-screensaver

    # Let users mount devices (i.e., and avoid having to use `caja` GUI).
    - pmount

