---

- name: "Install Ruby development packages"
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # Packages `ruby-install` installs unless --no-install-deps,
    # installed here so that ruby-install can be run sudolessly.
    - build-essential
    - bison
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev

    # Ruby make
    - rake

# ***

- name: "Install Ruby and related packages (Debian 12)"
  when: ansible_lsb.id == 'Debian' and ansible_lsb.major_release|int == 12
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    - ruby3.1
    - ruby3.1-dev
    - ruby3.1-doc

- name: "Install Ruby and related packages (Mint 21)"
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 21
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    - ruby3.0
    - ruby3.0-dev
    - ruby3.0-doc

- name: "Install Ruby and related packages (Mint 19)"
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 19
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    # Ubuntu 14.04: ruby 1.9
    # Ubuntu 16.04: ruby 2.3
    # Ubuntu 18.04: ruby 2.5
    - ruby2.5
    - ruby2.5-dev
    - ruby2.5-doc

- name: "Install Ruby and related packages (Mint 17/18)"
  when: ansible_lsb.id == 'LinuxMint' and (ansible_lsb.major_release|int in [17,18])
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:
    - ruby2.3
    - ruby2.3-dev
    - ruby2.3-doc

