---

- name: 'Install audio apps to play, burn, and streamrip'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # DVD burning software.
    - brasero

    # Audio Player.
    - clementine

    # 2018-12-14: I haven't streamripped in forever,
    # but here's one app I've trusted previously.
    - streamripper

