---

- name: 'Install audio apps to play, burn, and streamrip'
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:

    # "CD/DVD burning application for GNOME"
    - brasero

    # Audio Player.
    - clementine

    # 2025-09-23: For `paplay` (for DXY/bin/notify).
    - pulseaudio-utils

    # 2018-12-14: I haven't streamripped in forever,
    # but here's one app I've trusted previously.
    # "download online streams into audio files"
    - streamripper

# ***
