---

- name: "Install core desktop tools"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:

    # CLI OS and Window Manager customizers.
    - dconf-cli

    # These are essential on MATE (Linux Mint), but still work (to
    # some extent) on GNOME Shell (Debian).
    - wmctrl
    - xdotool

    # apt-file - search for files within Debian packages (command-line interface)
    - apt-file

    # "detect if we are running in a virtual machine"
    #  - virt-what

    # Eye of Gnome, a slideshow image viewer.
    # - Installed by default on Debian 12.
    - eog

    # [meld is the] Awesomest graphical diff.
    # REFER/2025-01-16: Because of circa 2020-02-04 issue with
    # meld (v3.18.0) from Linux Mint apt sources, this package
    # was skipped, and Meld was installed as a Flatpak instead.
    # - CXREF: See install-flatpaks.yml task in this role.
    #   - If you're in a DepoXy environment, found locally at:
    #     ~/.kit/ansible/roles/zoidy_captivator/tasks/install-flatpaks.yml
    # - But author's experience w/ Debian 12 Meld (v3.22.0) has
    #   been flawless.
    - meld

    # Hexadecimal file viewer.
    - ghex

    - hexedit

    # Hexadecimal diff.
    # [lb] I use ghex very rarely, and vbindiff less so,
    # but a hex viewer and a differ are essential tools.
    - vbindiff
    # Meh on hexdiff.
    #  - hexdiff

    # Color pickers.
    # - HSTRY/2018-12-15: Previously used gcolor2.
    #   - REFER: Some tips from people asking for alts:
    #       zenity --color-selection
    #       yad --color  # Like zenity, but not installed by default
    #       gpick
    #     https://askubuntu.com/questions/1073990/gcolor2-package-missing-in-ubuntu-18-04
    #   - NOTED: "gcolor3 does not have broad list of predefined colors".
    #
    # REFER: https://gitlab.gnome.org/World/gcolor3
    # "Simple GTK3 color selector and picker"
    - gcolor3
    # "advanced GTK+ color picker"
    - gpick

    # artha - "Handy off-line thesaurus based on WordNet"
    # HINT: After running, press Ctrl-Alt-W to foreground!
    # [lb]: I don't really use this, but like to know that
    # if I'm offline, I can find a dictionary & thesaurus.
    - artha

    # Let users mount devices (i.e., and avoid having to use `caja` GUI).
    - pmount

- name: "Install core desktop tools (Mint-only)"
  when: ansible_lsb.id == 'LinuxMint'
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:

    # Bleeding edge Chrome.
    - chromium-browser

- name: "Install core desktop tools (Debian-only)"
  when: ansible_lsb.id == 'Debian'
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:

    # Bleeding edge Chrome.
    - chromium

# ***
