---

- name: 'Install version control packages'
  become: true
  apt: name={{ item }}
  tags: install-develop-vcs
  loop:

    - git

    # GUI git log tool and commit comparison [visual diff] tool
    - gitk

    # GIT utilities [sic]
    - git-extras

    # A beautiful, colorful git browser/helper.
    # tig - ncurses-based text-mode interface for Git
    - tig

    # Just. In. Case. (Hopefully Never.)
    - subversion
    - mercurial

