---

- name: "Install some language-specific develop tools [that this developer has used]"
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # Count Lines Of Code ("statistics utility to count lines of code")
    - cloc

    # shellcheck - lint tool for shell scripts
    - shellcheck

    # Lua scripting.
    - lua5.4
    # 2023-03-24: Latest luaX.X-docs was 5.2, so guessing
    # (though unconfirmed if) part of base luaX.X install.
    #  - lua5.2-doc

    # Node.js and package manager.
    # - CXREF: See also nvm, a better way to manage Node versions.
    - nodejs
    - npm

    # Yaml linter. Because you always wanted more Yaml in your life.
    - yamllint

    # "Code coverage analysis using DWARF debugging information"
    - kcov

