---

- name: 'Install distro-specific packages for 16.04'
  when: ansible_lsb.id == 'LinuxMint' and ansible_lsb.major_release|int == 18
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # *** install-develop-core.yml

    # Color picker. [That's no longer available in 18.04.]
    - gcolor2

    # *** install-develop-dbms.yml

    # DUNNO/2025-01-15: This is the only place 'postgresql-server-dev'
    # referenced. So obviously I have used/needed for over a decade.
    - postgresql-server-dev-9.3

    # Interactive bash debugger. To set a breakpoint:
    #   source /usr/share/bashdb/bashdb-trace
    #   _Dbg_debugger
    # http://bashdb.sourceforge.net/
    - bashdb

    # *** install-develop-web.yml

    - apache2-mpm-worker

