---

- name: 'Install version control packages'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    - git

    # GUI git log tool and commit comparison [visual diff] tool
    - gitk

    # https://github.com/tj/git-extras
    - git-extras

    # A beautiful, colorful git browser/helper.
    # tig - ncurses-based text-mode interface for Git
    - tig

    # tig-newtons uses `dc` to generate a comment character
    # for the rebase todo, because there's no way to delimit
    # a comment character in tig config.
    # "GNU dc arbitrary precision reverse-polish calculator"
    - dc

    # Just. In. Case. (Hopefully Never.)
    - subversion
    - mercurial

