---

- name: 'Install terminal tools'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # tmux - terminal multiplexer
    - tmux

    # terminator - multiple GNOME terminals in one window
    - terminator
    # Avoid warnings, e.g.,
    #
    #   $ terminator -l <layout>
    #   Unable to load Keybinder module. This means the hide_window shortcut will be unavailable
    #   Unable to bind hide_window key, another instance/window has it.
    #
    # by installing recommended packages. Per package description:
    #
    #   $ apt-cache show terminator
    #   Version: 1.91-1
    #   Depends: python-cairo, ...
    #   Recommends: gir1.2-keybinder-3.0, gir1.2-notify-0.7, xdg-utils
    #
    # [lb]: With additional packages, I see one remaining warning, but whatever; e.g.,:
    #
    #   <window.Window object at 0x7f385ab506e0 (terminatorlib+window+Window at 0x55768b192290)>
    #     is not in registered window list
    #
    # gir1.2-keybinder-3.0 - registers global key bindings for applications - Gtk+3 - typelib
    # gir1.2-notify-0.7 - sends desktop notifications to a notification daemon (Introspection files)
    # xdg-utils - desktop integration utilities from freedesktop.org
    - gir1.2-keybinder-3.0
    - gir1.2-notify-0.7
    - xdg-utils

    # xclip - command line interface to X selections
    - xclip
    # http://www.vergenet.net/~conrad/software/xsel/
    # (lb): Do xclip and xsel have same features? This articles suggests so:
    #         https://fernandobasso.dev/shell/copy-paste-from-command-line-xclip-xsel-clipboard.html
    #       But AskUbuntu answer highlights different behavior in tmux:
    #         https://askubuntu.com/questions/705620/xclip-vs-xsel
    #       "xclip does not close STDOUT after it has read from tmux's buffer.
    #        As such, tmux doesn't know that the copy task has completed, and
    #        continues to wait for xclip's termination, thereby rendering tmux
    #        unresponsive. A workaround is to redirect STDOUT of xclip to /dev/null"
    #       - If you look in gpakosz/.tmux/.tmux.conf, you'll see `xclip >/dev/null 2>&1`.
    - xsel

    # *** Shell

    # direnv - An app I used to use, but not so much lately. At all
    #   "Utility to set directory specific environment variables"
    - direnv

    # expect - Automates interactive applications
    - expect

    # 2018-12-14: Is this needed for some Home Fries functionality?
    # libedit-dev - BSD editline and history libraries (development files)
    # FIXME/2018-12-14 18:55: Disabling for now! Revisit.
    #- libedit-dev

    # inotify-tools - command-line programs providing a simple interface to inotify
    - inotify-tools

    # Try mosh, as suggested by wonderful post of using Ansible to secure a
    # linux box (which I found while looking for task to regex sshd_config).
    #   https://ryaneschinger.com/blog/securing-a-server-with-ansible/
    # mosh - Mobile shell that supports roaming and intelligent local echo
    - mosh

    # Progress meter.
    # pv - Shell pipeline element to meter data passing through
    - pv

    # [lb] Maybe someday I'll try a shell other than Bash.
    #  (But why rock the boat when you've got a good thing?)
    # zsh - shell with lots of features
    - zsh

    # readline wrapper, e.g., a nice Perl REPL: rlwrap perl -d -e 1
    - rlwrap

