---

- name: 'Install audio tools'
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # DVD burning software.
    - brasero

    # Audio Player.
    - clementine

    # 2018-12-14: I haven't streamripped in forever,
    # but it's nice to know I can whenever I want.
    - streamripper

