---

- name: 'Install miscellaneously-categoried development applications'
  become: true
  apt: name={{ item }}
  tags: install-develop-misc
  loop:

    # 2016-09-30: Weird. I swore this was already part of setup.
    # 2016-10-03: I installed adb first, then android-tools-adb,
    # and the latter uninstalled the former. Hmmm.
    #   - adb
    - android-tools-adb

    - htop

    - logcheck
    - logcheck-database

    # mount.nfs
    - nfs-common

    # nslookup is... stale, to be polite. Use `dig` instead.

    # Un-Zip-a-Dee-Doo-Dah
    - unzip

    # Flicker the screen! (I'm using in CI script to indicate when build is ready.)
    #   xcalib -invert -alter
    - xcalib

