---

# Avoid error running deb822_repository module: "An exception
# occurred ... ModuleNotFoundError: No module named 'debian'".
- name: 'Install python3-debian for deb822_repository usage'
  become: true
  ansible.builtin.apt:
    name: python3-debian
    state: present

# REFER: See latest installation instructions:
#   https://www.spotify.com/us/download/linux/
# - Check periodically for changed key ID.
#
# SAVVY/2025-01-16: On Debian 12, creates sources file:
#     /etc/apt/sources.list.d/spotify.sources
- name: Add Spotify APT repository
  become: true
  ansible.builtin.deb822_repository:
    name: spotify
    types: [deb]
    uris: http://repository.spotify.com
    signed_by: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
    suites: [stable]
    components: [non-free]
    enabled: true

- name: Run command "apt-get update" (app-spotify)
  become: true
  ansible.builtin.apt:
    update_cache: yes
    # Ignore the cache timeout, i.e., always assume the spotify.sources
    # file was just created by the previous task (and that any previous
    # apt-get update wouldn't have downloaded its package list).
    #
    #  cache_valid_time: 3600

# NTRST: Without looping, doesn't print package name, e.g.:
#   This:
#     - name: 'Install Spotify desktop client application'
#       become: true
#       ansible.builtin.apt:
#         name: spotify-client
#         state: present
#   Prints this:
#     TASK [zoidy_captivator : Install Spotify desktop client application]
#     changed: [lethe]
#   Whereas the loop used below shows the item names, e.g.:
#     changed: [lethe] => (item=spotify-client)
- name: 'Install Spotify desktop client application'
  become: true
  ansible.builtin.apt:
    name: {{ item }}
  loop:
    - spotify-client
