---

- name: 'Install miscellaneously-categoried development applications'
  become: true
  apt: name={{ item }}
  tags: install-develop-misc
  loop:

    # 2016-09-30: Weird. I swore this was already part of setup.
    # 2016-10-03: I installed adb first, then android-tools-adb,
    # and the latter uninstalled the former. Hmmm.
    #   - adb
    - android-tools-adb

    # 2019-01-23: Mainly for git-committing dob plugin,
    #   ~/.config/dob/plugins/my_post_processor.py
    # cowsay - configurable talking cow
    - cowsay
    # cowsay-off - configurable talking cow (offensive cows)
    - cowsay-off
    # 2019-01-23: Saw this, too, but did not bother investigating what'is.
    # xcowsay - Graphical configurable talking cow
    # - xcowsay

    # BONUS!/2020-02-12: ``fd`` available in Ubuntu 19.04.
    # - This task'll still fail if you're on a old distro.
    #   - Just comment out the `fd-find`, sorry! Ha!!
    #     (It's simpler to document here than to make a new task
    #      that'll be removed soon because next distro includes fd.)
    #   - Then check for and install the latest release:
    #       sensible-browser https://github.com/sharkdp/fd/releases
    #       # E.g.,
    #       cd ~/.downloads
    #       wget https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb
    #       sudo dpkg -i fd_7.4.0_amd64.deb
    # FIXME/2020-02-12: Cleanup this comment someday.
    - fd-find

    - fdupes

    # fortune-mod - provides fortune cookies on demand
    - fortune-mod
    # fortunes - Data files containing fortune cookies
    # 2019-01-23: I removed fortunes, and /usr/share/games/fortunes
    #   still has: fortunes, literature, and riddles.
    - fortunes
    # Other fortune lists you'll find on `apt-cache search fortune`:
    # - fortunes-min - Data files containing selected fortune cookies
    #   - fortunes-min is just a subset of fortunes, looks like.
    # - fortunes-off - Data files containing offensive fortune cookies
    #   - `fortune -o`. Meh. Or, `fortune -a` to choose between off, and not.
    #     Not that clever. And I really just need noise, not something read.
    # - fortunes-bofh-excuses - BOFH excuses for fortune
    #   - From a time before cloud. Golden oldies such as:
    #       BOFH excuse #364:
    #       Sand fleas eating the Internet cables
    # - fortune-anarchism - anarchist quotes for fortune
    #   - `fortune anarchism`, if you want to leave America for a spell, e.g.,
    #       Order results spontaneously when things are let alone.
    #       ----+- Zhuangzi -+----
    - fortune-anarchism
    # - display-dhammapada - fortune-like collection of Buddhist sayings
    #   - Its own app, `display-dhammapada`; not sure where its files.

    - htop

    - jq

    - logcheck
    - logcheck-database

    # mount.nfs
    - nfs-common

    # nslookup is... stale, to be polite. Use `dig` instead.

    # Un-Zip-a-Dee-Doo-Dah
    - unzip

    # Flicker the screen! (I'm using in CI script to indicate when build is ready.)
    #   xcalib -invert -alter
    - xcalib

    # FIXME/2018-12-16: Home Fries requires direnv; make Home Fries Install Role.
    - direnv

    - tree

    # ScreenRuler project page:
    #
    #   https://gnomecoder.wordpress.com/screenruler/
    #
    # ScreenRulers source:
    #
    #   https://code.launchpad.net/screenruler
    - screenruler

