---

- name: 'Install network application development and diagnostic tools'
  become: true
  ansible.builtin.apt: name={{ item }}
  tags: install-develop-net
  loop:

    - curl

    - sshfs

    - traceroute

    - whois

    # *** Terminal-based Wireshark alternatives.

    # ssldump - SSLv3/TLS network protocol analyzer
    - ssldump

    # tshark - network traffic analyzer - console version
    - tshark

    - nmap

- name: 'Install network application development and diagnostic tools (Mint-only)'
  when: ansible_lsb.id == 'LinuxMint'
  become: true
  ansible.builtin.apt: name={{ item }}
  tags: install-develop-net
  loop:

    # 2025-01-15: Not found in Debian 12 sources.
    - socket

