---

- name: "Install Perl development packages"
  become: true
  ansible.builtin.apt: name={{ item }}
  loop:

    # 2019-10-28: For myrepos.
    - perl-doc

    # Perl debugger (perl -d) readline support (e.g., pressing up-arrow to
    # cycle through previously entered commands).
    - libterm-readline-gnu-perl

