---

- name: "Install some language-specific develop tools [that this developer has used]"
  become: true
  apt: name={{ item }}
  tags: install-develop-lang
  loop:

    # shellcheck - lint tool for shell scripts
    - shellcheck

    # Lua scripting.
    # 2018-12-15: lua5.3 released, but not docs for it.
    #- lua5.2
    - lua5.2-doc
    - lua5.3
    #- lua5.3-doc

    # Node.js and package manager.
    # - CXREF: See also nvm, a better way to manage Node versions.
    - nodejs
    - npm

    # Yaml linter. Because you always wanted more Yaml in your life.
    - yamllint

