---

# This task is similar to the GUI option:
#
#   MATE Menu > Update Manager > Edit > Preferences >
#   - Automation > ✓ Remove obsolete kernels and dependencies
#
# and creates the symlink:
#
#   /etc/systemd/system/timers.target.wants/mintupdate-automation-autoremove.timer
#     -> /lib/systemd/system/mintupdate-automation-autoremove.timer
#
# But using this approach, you won't see the "Remove obsolete..." option
# enabled in the GUI. Oh, well, run `systemctl list-timers` and you'll
# see that it's enabled..

# CXREF:
#
#   https://github.com/linuxmint/mintupdate/blob/master/lib/systemd/system/mintupdate-automation-autoremove.timer
#   https://github.com/linuxmint/mintupdate/blob/master/usr/share/linuxmint/mintupdate/automation/autoremove.sh

# REFER:
#
#   systemctl list-timers

# CXREF: Each of the timers, services, or scripts listed here calls the next one listed:
#   /etc/systemd/system/timers.target.wants/mintupdate-automation-autoremove.timer ->
#     /lib/systemd/system/mintupdate-automation-autoremove.timer
#   /lib/systemd/system/mintupdate-automation-upgrade.service
#   /usr/lib/linuxmint/mintUpdate/automatic_upgrades.py
#   /usr/bin/mintupdate-cli
#   /usr/lib/linuxmint/mintUpdate/mintupdate-cli.py

# E.g.,
#   sudo systemctl enable mintupdate-automation-autoremove.timer
- name: Enable a timer unit for mintupdate-automation-autoremove
  ansible.builtin.systemd:
    name: mintupdate-automation-autoremove.timer
    state: started
    enabled: true
  become: yes

