---

# SAVVY: In practice, on Resume, you'll see the unlocked screen for a brief
# moment before the screensaver kicks on, and then when you interact (move
# mouse, hit Escape, etc.), you'll get the password popup.

# Check systemctl to verify that this service is setup:
#
#   systemctl status power-suspend-lock-sessions.service

- name: Ensure session is locked on power suspension
  become: true
  ansible.builtin.template:
    src: power-suspend-lock-sessions.service
    dest: /etc/systemd/system

# `systemctl daemon-reload`
- name: Reload systemd configs, to see newly installed lock-on-suspend service
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

# E.g.,
#   systemctl enable power-suspend-lock-sessions.service
#   systemctl start power-suspend-lock-sessions.service
# Aka:
#   systemctl enable --now power-suspend-lock-sessions.service
- name: Start and Enable-on-boot Our lock-on-suspend service
  become: true
  ansible.builtin.systemd:
    name: power-suspend-lock-sessions.service
    # Ha! This locks the screen on ya when it runs!
    state: started
    enabled: yes

