---

# Update package list, and upgrade all packages, including distro pkgs.

- name: Run command "apt-get update" (update-upgrade)
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: update-upgrade, update

# This is a development machine, so would rather have
# conflicts resolved and maybe something broken, than
# upgrades not performed because snowflake. Therefore
# run a full/dist upgrade [which should be same: full
# and dist have unique documentation, but in the code
# apparently run the same code].

- name: Run command "apt full-upgrade", i.e., "apt-get upgrade"
  become: true
  apt:
    # upgrade: dist | full | no | safe | yes
    upgrade: full
  tags: update-upgrade, upgrade

